### ISSUE TITLE
v1.1.1 is incompatible with activerecord-deprecated_finders

### ISSUE THREAD

**Issue by staugaard** [khiav223577/rails_or#13]
When using `activerecord-deprecated_finders`, the `all` method on relation actually executes the query and returns an array.

https://github.com/rails/activerecord-deprecated_finders/blob/master/lib/active_record/deprecated_finders/relation.rb#L168

So you run into this `NoMethodError: undefined method `where_values=' for []:Array`

**Comment by khiav223577** [comment]
Thanks. It seems like the gem changes the default behavior of #all in Rails 4.

**Comment by khiav223577** [comment]
Just release v1.1.2
works fine with rails 4.2.7.1 and activerecord-deprecated_finders 1.0.4
